### ISSUE TITLE
Key error

### ISSUE THREAD

**Issue by 9mido** [TwilioDevEd/voice-javascript-sdk-quickstart-python#2]
Whenever I call I get the following traceback in django from request.POST['phone']:

```
@csrf_exempt
def phone(request):
    form = PhoneForm()

    if request.method == 'POST':
        print(request.POST['phone']) #comes from javascript phone: phoneNumberInput.value
        form = PhoneForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data.get("phone_number"))
            resp = VoiceResponse()
            resp.dial(str(request.POST['phone']), caller_id='+12345678909', action='/phone/', method='POST')
            return HttpResponse(str(resp), content_type='application/xml; charset=utf-8')


Internal Server Error: /phone/
Traceback (most recent call last):
  File "/home/name/.local/share/virtualenvs/project_name/lib/python3.8/site-packages/django/utils/datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'phone'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/name/.local/share/virtualenvs/project_name/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/name/.local/share/virtualenvs/project_name/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/name/.local/share/virtualenvs/project_name/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/name/video-membership-master/phone/views.py", line 78, in phone
    print(request.POST['phone']) #comes from javascript phone: phoneNumberInput.value
  File "/home/name/.local/share/virtualenvs/project_name/lib/python3.8/site-packages/django/utils/datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'phone'
```

**Comment by sarahcstringer** [comment]
Hi @9mido -- can you clarify when this happens? Is it when you enter a number in the browser form and click "Call"?
Are you able to see [this console.log line](https://github.com/TwilioDevEd/voice-javascript-sdk-quickstart-python/blob/main/static/quickstart.js#L112) in the browser console?

**Comment by 9mido** [comment]
Yes when I enter a verified number and click "Call" with request.POST['phone']. The outgoing call goes through to the typed in phone number and it works. But my terminal shows the traceback above. Yes that line you linked I am able to see in the Events Log from the template not the browser console inspection tool. 

If I use request.POST.get("phone") I do not get the same key error. But when I try making an outgoing call to the phone number I type in when using request.POST.get("phone"), the call goes through, but the terminal keeps showing POST requests to my /phone/ URL over and over as if it is an infinite loop when the outgoing phone I am calling to hangs up before the web browser user does. But this infinite loop happens when I have action='/phone/'. Deleting the action solved the problem. 

```
@csrf_exempt
def phone(request):
    form = PhoneForm()
    if request.method == 'POST':
        print(request.POST.get("phone"))
        resp = VoiceResponse()
        resp.dial(request.POST.get("phone"), caller_id='+12345678909', action='/phone/', method='POST')
        return HttpResponse(str(resp), content_type='application/xml; charset=utf-8')
    return render(request, 'phone.html', { 'form': form })
```
