### ISSUE TITLE
Unable to create record: No 'To' number is specified

### ISSUE THREAD

**Issue by 9mido** [TwilioDevEd/voice-javascript-sdk-quickstart-python#8]
If I make an outbound call using the docs way of doing it and enter a To phone number in the form input and use the following code I get the following error and traceback. Strangely, the outbound call goes through successfully to the typed in To number and the TwiML gets executed if the To number you call presses any key. 

```
account_sid = 'XXXXXXXXXX'
auth_token = 'XXXXXXXXXXX'
client = Client(account_sid, auth_token)

if request.method == 'POST' and request.POST.get('To') is not None:
    call = client.calls.create(twiml='<Response><Say>Ahoy there!</Say></Response>',to=request.POST.get('To'),from_='+12345678909')
```

```
Traceback (most recent call last):
  File "/home/name/.local/share/virtualenvs/project_name/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/name/.local/share/virtualenvs/project_name/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/name/.local/share/virtualenvs/project_name/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/name/project_name/phone/views.py", line 148, in phone
    call = client.calls.create(twiml='<Response><Say>Ahoy there!</Say></Response>',to=request.POST.get('To'),from_='+12345678909')
  File "/home/name/.local/share/virtualenvs/project_name/lib/python3.8/site-packages/twilio/rest/api/v2010/account/call/__init__.py", line 146, in create
    payload = self._version.create(method='POST', uri=self._uri, data=data, )
  File "/home/name/.local/share/virtualenvs/project_name/lib/python3.8/site-packages/twilio/base/version.py", line 205, in create
    raise self.exception(method, uri, response, 'Unable to create record')
twilio.base.exceptions.TwilioRestException: 
```

**Comment by bld010** [comment]
Hm. I think I would need to see your `app.py` and `quickstart.js` files to find out what's going on here, but I'll give you some recommendations for what I think may be going on.

I'm assuming by 'the docs way of doing it' you are referring to [this page](https://www.twilio.com/docs/voice/tutorials/how-to-make-outbound-phone-calls-python)?

With this Quickstart, we're calling [`device.connect()`](https://www.twilio.com/docs/voice/sdks/javascript/twiliodevice#deviceconnectconnectoptions) when you're attempting to make an outbound call. This will then trigger a request to the TwiML application you created. The TwiML application is pointed to your application's `/voice` endpoint (you configured this in your Twilio Console). 

It may be helpful to use a `print()` command within your `/voice` endpoint in your `app.py` file to check out what's being sent over from that `device.connect()` call. Since your code above is expecting a `To:` field, make sure that you're sending over a `To:` field from your `device.connect({ params })` invocation in `makeOutgoingCall` in `quickstart.js`. 

There is an [open PR](https://github.com/TwilioDevEd/voice-javascript-sdk-quickstart-python/pull/6) right now that has the updates we discussed last week. I'd check out the `makeOutgoingCall` function in `quickstart.js` and notice how we're passing the `To:` parameter to your TwiML application (and thereby your `/voice` endpoint). You may need to change your project's `makeOutgoingCall` method to use `To:` rather than `phone:` so that it matches your code above.

**Comment by 9mido** [comment]
I am using the newer version of the quickstart.js code that you made an update to where it uses To. Quickstart.js is the same as yours except the token url path. The token python function is the same as yours and the other voice function to make the call just contains just the code from the docs which is what you see above. 

Yes I am referring to that page of the docs.

The To field phone number does get printed when I make the call in my terminal when I do `print(request.POST.get('To'))` and `print(call.sid)` also shows something.

**Comment by bld010** [comment]
Hm... Can you push your project up to a public GitHub repo? Or can you copy and paste your `app.js` and `quickstart.js` files here? Alternatively, you can email me at the Twilio email in my GitHub profile.

**Comment by 9mido** [comment]
Webhooks are setup to /phone/ which is where function phone() lives. 

```
def token(request):
    #This should be a phone number from the user from the database
    identity = 'user'

    # Create access token with credentials
    #account sid, api sid, api secret
    access_token = AccessToken('XXXXXXXXX', 'XXXXXXXXX', 'XXXXXXXXXx', identity=identity)

    # Create a Voice grant and add to token
    #outgoing_application_sid = twiml application for webhooks
    voice_grant = VoiceGrant(
        outgoing_application_sid='XXXXXXXXXx',
        incoming_allow=True, # Optional: add to allow incoming calls
    )
    access_token.add_grant(voice_grant)

    token = access_token.to_jwt()

    return JsonResponse({'token': token.decode('utf-8'), 'identity':identity})

@csrf_exempt
def phone(request):
    form = PhoneForm()

    account_sid = 'XXXXXXXX'
    auth_token = 'XXXXXXXX
    client = Client(account_sid, auth_token)

    if request.method == 'POST' and request.POST.get('To') is not None:
        client = Client('XXXXXXXXXX','XXXXXXXXX')
        call = client.calls.create(url=request.build_absolute_uri() + '/phone/',to=str(request.POST.get('To')),from_='+12345678909')
        print(call.sid)

    return render(request, 'phone.html', { 'form': form })

```



```
<script>

$(function () {
  const speakerDevices = document.getElementById("speaker-devices");
  const ringtoneDevices = document.getElementById("ringtone-devices");
  const outputVolumeBar = document.getElementById("output-volume");
  const inputVolumeBar = document.getElementById("input-volume");
  const volumeIndicators = document.getElementById("volume-indicators");
  const callButton = document.getElementById("button-call");
  const outgoingCallHangupButton = document.getElementById("button-hangup-outgoing");
  const callControlsDiv = document.getElementById("call-controls");
  const audioSelectionDiv = document.getElementById("output-selection");
  const getAudioDevicesButton = document.getElementById("get-devices");
  const logDiv = document.getElementById("log");
  const incomingCallDiv = document.getElementById("incoming-call");
  const incomingCallHangupButton = document.getElementById(
    "button-hangup-incoming"
  );
  const incomingCallAcceptButton = document.getElementById(
    "button-accept-incoming"
  );
  const incomingCallRejectButton = document.getElementById(
    "button-reject-incoming"
  );
  const phoneNumberInput = document.getElementById("phone-number");
  const incomingPhoneNumberEl = document.getElementById("incoming-number");
  const startupButton = document.getElementById("startup-button");
const muteButton = document.getElementById("button-mute");

  let device;
  let token;

  // Event Listeners

  callButton.onclick = (e) => {
    e.preventDefault();
    makeOutgoingCall();
  };
  getAudioDevicesButton.onclick = getAudioDevices;
  speakerDevices.addEventListener("change", updateOutputDevice);
  ringtoneDevices.addEventListener("change", updateRingtoneDevice);
  

  // SETUP STEP 1:
  // Browser client should be started after a user gesture
  // to avoid errors in the browser console re: AudioContext
  startupButton.addEventListener("click", startupClient);

  // SETUP STEP 2: Request an Access Token
  async function startupClient() {
    log("Requesting Access Token...");

    try {
      const data = await $.getJSON("/phone/token/");
      log("Got a token.");
      token = data.token;
      setClientNameUI(data.identity);
      intitializeDevice();
    } catch (err) {
      console.log(err);
      log("An error occurred. See your browser console for more information.");
    }
  }

  // SETUP STEP 3:
  // Instantiate a new Twilio.Device
  function intitializeDevice() {
    logDiv.classList.remove("hide");
    log("Initializing device");
    device = new Twilio.Device(token, {
      debug: true,
      answerOnBridge: true,
      // Set Opus as our preferred codec. Opus generally performs better, requiring less bandwidth and
      // providing better audio quality in restrained network conditions. Opus will be default in 2.0.
      codecPreferences: ["opus", "pcmu"],
    });

    addDeviceListeners(device);

    // Device must be registered in order to receive incoming calls
    device.register();
  }

  // SETUP STEP 4:
  // Listen for Twilio.Device states
  function addDeviceListeners(device) {
    device.on("registered", function () {
      log("Twilio.Device Ready to make and receive calls!");
      callControlsDiv.classList.remove("hide");
    });

    device.on("error", function (error) {
      log("Twilio.Device Error: " + error.message);
    });

    device.on("incoming", handleIncomingCall);

    device.audio.on("deviceChange", updateAllAudioDevices.bind(device));

    // Show audio selection UI if it is supported by the browser.
    if (device.audio.isOutputSelectionSupported) {
      audioSelectionDiv.classList.remove("hide");
    }
  }

  function toggleMute(call) {
    if (call && call.status() === "open") {
        call.mute(!call.isMuted());
        log(`Call is muted: ${call.isMuted()}`)
     }
  }

  // MAKE AN OUTGOING CALL

  async function makeOutgoingCall() {
    var params = {
      // get the phone number to call from the DOM
      To: phoneNumberInput.value,
    };

    if (device) {
      log(`Attempting to call ${params.To} ...`);

      // Twilio.Device.connect() returns a Call object
      const call = await device.connect({ params });

      // add listeners to the Call
      // "accepted" means the call has finished connecting and the state is now "open"
      call.on("accept", updateUIAcceptedOutgoingCall);
      call.on("disconnect", updateUIDisconnectedOutgoingCall);
      call.on("cancel", updateUIDisconnectedOutgoingCall);
      call.on("reject", updateUIDisconnectedOutgoingCall);

      outgoingCallHangupButton.onclick = () => {
        log("Hanging up ...");
        call.disconnect();
      };

  muteButton.onclick = () => {
     toggleMute(call);
   }

    } else {
      log("Unable to make call.");
    }
  }

  function updateUIAcceptedOutgoingCall(call) {
    log("Call in progress ...");
    callButton.disabled = true;
    outgoingCallHangupButton.classList.remove("hide");
    volumeIndicators.classList.remove("hide");
    bindVolumeIndicators(call);
  }

  function updateUIDisconnectedOutgoingCall() {
    log("Call disconnected.");
    callButton.disabled = false;
    outgoingCallHangupButton.classList.add("hide");
    volumeIndicators.classList.add("hide");
  }

  // HANDLE INCOMING CALL

  function handleIncomingCall(call) {
    log(`Incoming call from ${call.parameters.From}`);

    //show incoming call div and incoming phone number
    incomingCallDiv.classList.remove("hide");
    incomingPhoneNumberEl.innerHTML = call.parameters.From;

    //add event listeners for Accept, Reject, and Hangup buttons
    incomingCallAcceptButton.onclick = () => {
      acceptIncomingCall(call);
    };

    incomingCallRejectButton.onclick = () => {
      rejectIncomingCall(call);
    };

    incomingCallHangupButton.onclick = () => {
      hangupIncomingCall(call);
    };

muteButton.onclick = () => {
  toggleMute(call);
}

    // add event listener to call object
    call.on("cancel", handleDisconnectedIncomingCall);
    call.on("disconnect", handleDisconnectedIncomingCall);
    call.on("reject", handleDisconnectedIncomingCall);
  }

  // ACCEPT INCOMING CALL

  function acceptIncomingCall(call) {
    call.accept();

    //update UI
    log("Accepted incoming call.");
    incomingCallAcceptButton.classList.add("hide");
    incomingCallRejectButton.classList.add("hide");
    incomingCallHangupButton.classList.remove("hide");
  }

  // REJECT INCOMING CALL

  function rejectIncomingCall(call) {
    call.reject();
    log("Rejected incoming call");
    resetIncomingCallUI();
  }

  // HANG UP INCOMING CALL

  function hangupIncomingCall(call) {
    call.disconnect();
    log("Hanging up incoming call");
    resetIncomingCallUI();
  }

  // HANDLE CANCELLED INCOMING CALL

  function handleDisconnectedIncomingCall() {
    log("Incoming call ended.");
    resetIncomingCallUI();
  }

  // MISC USER INTERFACE

  // Activity log
  function log(message) {
    logDiv.innerHTML += `<p class="log-entry">&gt;&nbsp; ${message} </p>`;
    logDiv.scrollTop = logDiv.scrollHeight;
  }

  function setClientNameUI(clientName) {
    var div = document.getElementById("client-name");
    div.innerHTML = `Your client name: <strong>${clientName}</strong>`;
  }

  function resetIncomingCallUI() {
    incomingPhoneNumberEl.innerHTML = "";
    incomingCallAcceptButton.classList.remove("hide");
    incomingCallRejectButton.classList.remove("hide");
    incomingCallHangupButton.classList.add("hide");
    incomingCallDiv.classList.add("hide");
  }

  // AUDIO CONTROLS

  async function getAudioDevices() {
    await navigator.mediaDevices.getUserMedia({ audio: true });
    updateAllAudioDevices.bind(device);
  }

  function updateAllAudioDevices() {
    if (device) {
      updateDevices(speakerDevices, device.audio.speakerDevices.get());
      updateDevices(ringtoneDevices, device.audio.ringtoneDevices.get());
    }
  }

  function updateOutputDevice() {
    const selectedDevices = Array.from(speakerDevices.children)
      .filter((node) => node.selected)
      .map((node) => node.getAttribute("data-id"));

    device.audio.speakerDevices.set(selectedDevices);
  }

  function updateRingtoneDevice() {
    const selectedDevices = Array.from(ringtoneDevices.children)
      .filter((node) => node.selected)
      .map((node) => node.getAttribute("data-id"));

    device.audio.ringtoneDevices.set(selectedDevices);
  }

  function bindVolumeIndicators(call) {
    call.on("volume", function (inputVolume, outputVolume) {
      var inputColor = "red";
      if (inputVolume < 0.5) {
        inputColor = "green";
      } else if (inputVolume < 0.75) {
        inputColor = "yellow";
      }

      inputVolumeBar.style.width = Math.floor(inputVolume * 300) + "px";
      inputVolumeBar.style.background = inputColor;

      var outputColor = "red";
      if (outputVolume < 0.5) {
        outputColor = "green";
      } else if (outputVolume < 0.75) {
        outputColor = "yellow";
      }

      outputVolumeBar.style.width = Math.floor(outputVolume * 300) + "px";
      outputVolumeBar.style.background = outputColor;
    });
  }

  // Update the available ringtone and speaker devices
  function updateDevices(selectEl, selectedDevices) {
    selectEl.innerHTML = "";

    device.audio.availableOutputDevices.forEach(function (device, id) {
      var isActive = selectedDevices.size === 0 && id === "default";
      selectedDevices.forEach(function (device) {
        if (device.deviceId === id) {
          isActive = true;
        }
      });

      var option = document.createElement("option");
      option.label = device.label;
      option.setAttribute("data-id", id);
      if (isActive) {
        option.setAttribute("selected", "selected");
      }
      selectEl.appendChild(option);
    });
  }
});

</script>

```

**Comment by bld010** [comment]
Thanks for posting those! 

In our quickstart.js file, when we call `device.connect()`, we are sending a POST request to our TwiML application, which is configured to send a POST request to our `/voice` endpoint. 

Twilio is expecting TwiML (XML) in response to that POST request to the `/voice` endpoint. This is why you see  `return Response(str(resp), mimetype="text/xml")` in the `/voice` endpoint. 

The SDK takes care of creating a Call for you. You don't need to create a new call like in those docs above. Those are just for server-side only creation of calls. You just need to return TwiML using the VoiceResponse() method from the helper library. The image below from the [Voice SDK Docs](https://www.twilio.com/docs/voice/sdks/javascript) may help:

![Voice JS SDK Diagram](https://twilio-cms-prod.s3.amazonaws.com/images/Voice_JS_SDK_Diagram.width-800.png)

**Comment by 9mido** [comment]
So I should ignore the docs method and do what I have showed you in other issues on this github project and always return TwiML? 

I would only use the docs way of doing it if I did not have the javascript SDK? 

The whole objective I am trying to accomplish is operate calls in the browser. So I always need to use javascript SDK? 

What is the point of making calls server side with the docs method if you cannot directly answer them on the browser?

**Comment by bld010** [comment]
Yes, if you only want to use the browser, the SDK is the way to go, meaning you should always return TwiML.

Some reasons someone may want to use the server-side only tools would be: sending automated messages to customers or setting up a phone-tree ("Press 3 to reach HR, press 4 to reach Engineering" or something like that) or setting up a SIP interface. 

I'm not sure you'd be able to make a browser phone with just Django without a lot of lifting. The SDK does the work of creating WebRTC connections and handling audio devices in the browser, and JavaScript is kind of a necessary evil when it comes to web browsers. 

You might, however, be able use Twilio's SIP functionality to connect a soft phone like Zoiper. Not browser-based, but still a soft phone that you can manage with Twilio's server-side functionality.
